name: .NET Build and Release

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 4.8.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Package the app
      run: dotnet publish -c Release -o ./publish

    - name: Get version from .csproj
      id: get_version
      run: echo "::set-output name=version::$(grep -oPm1 '(?<=<Version>)[^<]+' YourProject.csproj)"

    - name: Archive the package
      uses: actions/upload-artifact@v3
      with:
        name: my-app
        path: ./publish

  release:

    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 4.8.x

    - name: Download Build Artifact
      uses: actions/download-artifact@v3
      with:
        name: my-app

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.get_version.outputs.version }}
        release_name: Release v${{ steps.get_version.outputs.version }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./publish
        asset_name: my-app.zip
        asset_content_type: application/zip
