name: Build and Publish .NET Library to GitHub Releases

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x' 

      - name: Restore dependencies
        run: dotnet restore DiscordWebhookWrapper.csproj

      - name: Build project
        run: dotnet build DiscordWebhookWrapper.csproj --configuration Release

      - name: Publish project
        run: dotnet publish DiscordWebhookWrapper.csproj --configuration Release --output ./output

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ env.version }}
          release_name: Release v${{ env.version }}
          body: |
            ## Release Notes
            - New Build for Commit v${{ env.version }}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload DLL to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./output/YourLibrary.dll
          asset_name: YourLibrary.dll
          asset_content_type: application/octet-stream
